%funcdesc = (
'ABORT', 'Quit at once',
'ACCESSKEY', 'Pop up accesskey menu',
'ADD_BOOKMARK', 'Add current page to bookmarks',
'ALARM', 'Set alarm',
'BACK', 'Close current buffer and return to the one below in stack',
'BEGIN', 'Go to the first line',
'BOOKMARK', 'View bookmarks',
'CENTER_H', 'Center on cursor column',
'CENTER_V', 'Center on cursor line',
'CHARSET', 'Change the character encoding for the current document',
'CLOSE_TAB', 'Close tab',
'CLOSE_TAB_MOUSE', 'Close tab at mouse pointer',
'COMMAND', 'Invoke w3m function(s)',
'COOKIE', 'View cookie list',
'DEFAULT_CHARSET', 'Change the default character encoding',
'DEFINE_KEY', 'Define a binding between a key stroke combination and a command',
'DELETE_PREVBUF', 'Delete previous buffer (mainly for local CGI-scripts)',
'DICT_WORD', 'Execute dictionary command (see README.dict)',
'DICT_WORD_AT', 'Execute dictionary command for word at cursor',
'DISPLAY_IMAGE', 'Restart loading and drawing of images',
'DOWN', 'Scroll the screen down one line',
'DOWNLOAD', 'Save document source',
'DOWNLOAD_LIST', 'Display downloads panel',
'EDIT', 'Edit local source',
'EDIT_SCREEN', 'Edit rendered copy of document',
'END', 'Go to the last line',
'EXEC_SHELL', 'Execute shell command and display output',
'EXIT', 'Quit at once',
'EXTERN', 'Display using an external browser',
'EXTERN_LINK', 'Display target using an external browser',
'FRAME', 'Toggle rendering HTML frames',
'GOTO', 'Open specified document in a new buffer',
'GOTO_LINE', 'Go to the specified line',
'GOTO_LINK', 'Follow current hyperlink in a new buffer',
'GOTO_RELATIVE', 'Go to relative address',
'HELP', 'Show help panel',
'HISTORY', 'Show browsing history',
'INFO', 'Display information about the current document',
'INTERRUPT', 'Suspend w3m to background',
'ISEARCH', 'Incremental search forward',
'ISEARCH_BACK', 'Incremental search backward',
'LEFT', 'Shift screen one column left',
'LINE_BEGIN', 'Go to the beginning of the line',
'LINE_END', 'Go to the end of the line',
'LINE_INFO', 'Display current position in document',
'LINK_BEGIN', 'Move to the first hyperlink',
'LINK_END', 'Move to the last hyperlink',
'LINK_MENU', 'Pop up link element menu',
'LIST', 'Show all URLs referenced',
'LIST_MENU', 'Pop up menu for hyperlinks to browse to',
'LOAD', 'Open local file in a new buffer',
'MAIN_MENU', 'Pop up menu',
'MARK', 'Set/unset mark',
'MARK_MID', 'Turn Message-ID-like strings into hyperlinks',
'MARK_URL', 'Turn URL-like strings into hyperlinks',
'MARK_WORD', 'Turn current word into hyperlink',
'MENU', 'Pop up menu',
'MENU_MOUSE', 'Pop up menu at mouse pointer',
'MOUSE_TOGGLE', 'Toggle mouse support',
'MOVE_DOWN', 'Cursor down',
'MOVE_DOWN1', 'Cursor down. With edge touched, slide',
'MOVE_LEFT', 'Cursor left',
'MOVE_LEFT1', 'Cursor left. With edge touched, slide',
'MOVE_LIST_MENU', 'Pop up menu to navigate between hyperlinks',
'MOVE_MOUSE', 'Move cursor to mouse pointer',
'MOVE_RIGHT', 'Cursor right',
'MOVE_RIGHT1', 'Cursor right. With edge touched, slide',
'MOVE_UP', 'Cursor up',
'MOVE_UP1', 'Cursor up. With edge touched, slide',
'MSGS', 'Display error messages',
'NEW_TAB', 'Open a new tab (with current document)',
'NEXT', 'Switch to the next buffer',
'NEXT_DOWN', 'Move downward to the next hyperlink',
'NEXT_HALF_PAGE', 'Scroll down half a page',
'NEXT_LEFT', 'Move left to the next hyperlink',
'NEXT_LEFT_UP', 'Move left or upward to the next hyperlink',
'NEXT_LINK', 'Move to the next hyperlink',
'NEXT_MARK', 'Go to the next mark',
'NEXT_PAGE', 'Scroll down one page',
'NEXT_RIGHT', 'Move right to the next hyperlink',
'NEXT_RIGHT_DOWN', 'Move right or downward to the next hyperlink',
'NEXT_TAB', 'Switch to the next tab',
'NEXT_UP', 'Move upward to the next hyperlink',
'NEXT_VISITED', 'Move to the next visited hyperlink',
'NEXT_WORD', 'Move to the next word',
'NOTHING', 'Do nothing',
'NULL', 'Do nothing',
'OPTIONS', 'Display options setting panel',
'PEEK', 'Show current address',
'PEEK_IMG', 'Show image address',
'PEEK_LINK', 'Show target address',
'PIPE_BUF', 'Pipe current buffer through a shell command and display output',
'PIPE_SHELL', 'Execute shell command and display output',
'PREV', 'Switch to the previous buffer',
'PREV_HALF_PAGE', 'Scroll up half a page',
'PREV_LINK', 'Move to the previous hyperlink',
'PREV_MARK', 'Go to the previous mark',
'PREV_PAGE', 'Scroll up one page',
'PREV_TAB', 'Switch to the previous tab',
'PREV_VISITED', 'Move to the previous visited hyperlink',
'PREV_WORD', 'Move to the previous word',
'PRINT', 'Save rendered document',
'QUIT', 'Quit with confirmation request',
'READ_SHELL', 'Execute shell command and display output',
'REDO', 'Cancel the last undo',
'REDRAW', 'Draw the screen anew',
'REG_MARK', 'Mark all occurences of a pattern',
'REINIT', 'Reload configuration file',
'RELOAD', 'Load current document anew',
'RESHAPE', 'Re-render document',
'RIGHT', 'Shift screen one column right',
'SAVE', 'Save document source',
'SAVE_IMAGE', 'Save inline image',
'SAVE_LINK', 'Save hyperlink target',
'SAVE_SCREEN', 'Save rendered document',
'SEARCH', 'Search forward',
'SEARCH_BACK', 'Search backward',
'SEARCH_FORE', 'Search forward',
'SEARCH_NEXT', 'Continue search forward',
'SEARCH_PREV', 'Continue search backward',
'SELECT', 'Display buffer-stack panel',
'SELECT_MENU', 'Pop up buffer-stack menu',
'SETENV', 'Set environment variable',
'SET_OPTION', 'Set option',
'SHELL', 'Execute shell command and display output',
'SHIFT_LEFT', 'Shift screen left',
'SHIFT_RIGHT', 'Shift screen right',
'SOURCE', 'Toggle between HTML shown or processed',
'STOP_IMAGE', 'Stop loading and drawing of images',
'SUBMIT', 'Submit form',
'SUSPEND', 'Suspend w3m to background',
'TAB_GOTO', 'Open specified document in a new tab',
'TAB_GOTO_RELATIVE', 'Open relative address in a new tab',
'TAB_LEFT', 'Move left along the tab bar',
'TAB_LINK', 'Follow current hyperlink in a new tab',
'TAB_MENU', 'Pop up tab selection menu',
'TAB_MOUSE', 'Select tab by mouse action',
'TAB_RIGHT', 'Move right along the tab bar',
'UNDO', 'Cancel the last cursor movement',
'UP', 'Scroll the screen up one line',
'VERSION', 'Display the version of w3m',
'VIEW', 'Toggle between HTML shown or processed',
'VIEW_BOOKMARK', 'View bookmarks',
'VIEW_IMAGE', 'Display image in viewer',
'WHEREIS', 'Search forward',
'WRAP_TOGGLE', 'Toggle wrapping mode in searches',
);
# charset
$charset = 'US-ASCII';

# Buffer selection mode

%buf_funcdesc = (
 'BUF:PREV', 'Previous item',
 'BUF:NEXT', 'Next item',
 'BUF:DELETE', 'Delete item',
 'BUF:GO', 'Select item',
);

%lineedit_funcdesc = (
 'LINEEDIT:FORWARD', 'Cursor forward',
 'LINEEDIT:BACK', 'Cursor backward',
 'LINEEDIT:BS',  'Delete previous character',
 'LINEEDIT:DEL', 'Delete character',
 'LINEEDIT:KILL_AFTER', 'Delete everything after cursor',
 'LINEEDIT:KILL_BEFORE', 'Delete everything before cursor',
 'LINEEDIT:TOP', 'Cursor to the beginning of the line',
 'LINEEDIT:BOTTOM', 'Cursor to the end of the line',
 'LINEEDIT:PREV', 'Fetch the previous string from the history list',
 'LINEEDIT:NEXT', 'Fetch the next string from the history list',
 'LINEEDIT:EDITOR', 'Edit with external editor',
 'LINEEDIT:COMPLETE', 'Try to complete filename',
 'LINEEDIT:ACCEPT', 'Accept input line',
);

%menu_funcdesc = (
 'MENU:SELECT', 'Select item',
 'MENU:CLOSE', 'Close menu',
 'MENU:CANCEL', 'One selection step backward',
 'MENU:DOWN', 'Move to the next item',
 'MENU:UP', 'Move to the previous item',
 'MENU:LINE_UP', 'Scroll up one item',
 'MENU:LINE_DOWN', 'Scroll down one item',
 'MENU:TOP', 'Move to the first item',
 'MENU:LAST', 'Move to the final item',
 'MENU:NEXT', 'Go to the next page',
 'MENU:PREV', 'Go to the previous page',
 'MENU:SEARCH_FORE', 'Search forward',
 'MENU:SEARCH_BACK', 'Search backward',
 'MENU:SEARCH_NEXT', 'Search for the next match',
 'MENU:SEARCH_PREV', 'Search for the previous match',
 'MENU:SUSPEND', 'Suspend',
);

1;
